/* =========================================================================
   CLAIM_CONTACT_ROLE_LOOKUP - Motor rows, fresh INSERT (v3)
   205 rows. All previously-flagged duplicate keys now RESOLVED with real
   confirmed numbers (either from your own already-deployed sample data,
   or from the corrected block you provided directly):
     (55, 95/96)  TP Vehicle Owner=95, Registered Keeper=96 - both included
     (55, 98/99)  Company=98, Alleged Vandal=99 - both included
     (62, 41/43)  Mother=41, Brother=43 - both included
   Additionally corrected during the same cross-check (these were wrong
   in the original transcription, not duplicates, but real wrong numbers
   caught only because you supplied the correct HDR=62 block for
   comparison): Personal Assistant 139->138, Neighbour 239->139,
   Friend 148->140, Son 158->156, Spouse/Partner 260->280.

   IMPORTANT: given that HALF of one 12-row block (HDR_TYPE_ID=62) turned
   out to have wrong LINK_TYPEID numbers, there is a real chance similar
   errors exist elsewhere in this INSERT that have not yet been caught -
   this was only found because you happened to re-supply that one block
   for a different reason. A full reconciliation against the real,
   complete sheet (the Excel VLOOKUP approach described earlier) is
   strongly recommended before trusting this file completely.

   Still excluded, pending answers: 5 exception rows (10,11,12,41,211 -
   handled via MANDATORY_* CTEs). Row 131 ('Accident Location') has
   Link_to_Incident = NULL since the sheet says 'NC', not YES/NO.
   ========================================================================= */

INSERT INTO dbo.CLAIM_CONTACT_ROLE_LOOKUP
(HDR_TYPEID, HDR_TYPE, LINK_TYPEID, LINK_TYPE, PRODUCT, EXPOSURE, RISKUNIT_COVERABLE_TYPE,
 GWCC_Role_TYPECODE, GWCC_Role_Description, Link_to_Policy, Link_to_Exposure, Link_to_Incident)
VALUES
(44, N'Policy Holder', 44, N'Sister', N'Motor', N'GW HEADER CASE', NULL, N'policyholder', N'Policy holder', N'YES', N'NO', N'NO'),
(44, N'Policy Holder', 49, N'Next of Kin', N'Motor', N'GW HEADER CASE', NULL, N'policyholder', N'Policy holder', N'YES', N'NO', N'NO'),
(44, N'Policy Holder', 51, N'Correspondence Information', N'Motor', N'GW HEADER CASE', NULL, N'policyholder', N'Policy holder', N'YES', N'NO', N'NO'),
(44, N'Policy Holder', 109, N'Executor of Will', N'Motor', N'GW HEADER CASE', NULL, N'policyholder', N'Policy holder', N'YES', N'NO', N'NO'),
(44, N'Policy Holder', 231, N'Policy Holder', N'Motor', N'GW HEADER CASE', NULL, N'policyholder', N'Policy holder', N'YES', N'NO', N'NO'),
(44, N'Policy Holder', 253, N'Correspondence Information', N'Motor', N'GW HEADER CASE', NULL, N'policyholder', N'Policy holder', N'YES', N'NO', N'NO'),
(44, N'Policy Holder', 10005, N'Next of Kin', N'Motor', N'GW HEADER CASE', NULL, N'policyholder', N'Policy holder', N'YES', N'NO', N'NO'),
(51, N'Approved Repairer', 52, N'Bodyshop', N'Motor', N'GW MOTOR AD', NULL, N'repairshop', N'Approved Repairer', N'NO', N'NO', N'NO'),
(51, N'Approved Repairer', 53, N'Payee', N'Motor', N'GW MOTOR AD', NULL, N'repairshop', N'Approved Repairer', N'NO', N'NO', N'NO'),
(51, N'Approved Repairer', 3062, N'Hub Instructed Bodyshop', N'Motor', N'GW MOTOR AD', NULL, N'repairshop', N'Approved Repairer', N'NO', N'NO', N'NO'),
(52, N'TP Insurer', 108, N'TPI', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'tpinsurer_adm', N'TP Insurer', N'NO', N'NO', N'YES'),
(53, N'NON AR', 80, N'Bodyshop', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'nonapprovedrepairer_adm', N'Non - Approved Repairer', N'NO', N'YES', N'NO'),
(53, N'NON AR', 9991, N'Payee', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'nonapprovedrepairer_adm', N'Non - Approved Repairer', N'NO', N'YES', N'NO'),
(55, N'Third Party', 81, N'TP Driver', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdpartydriver_adm', N'Third Party Driver', N'NO', N'YES', N'NO'),
(55, N'Third Party', 82, N'TP Driver & Owner', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdpartydriver_adm', N'Third Party Driver', N'NO', N'YES', N'NO'),
(55, N'Third Party', 83, N'Next of Kin', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdparty_adm', N'Third Party', N'NO', N'NO', N'YES'),
(55, N'Third Party', 84, N'Correspondence Information', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdparty_adm', N'Third Party', N'NO', N'NO', N'YES'),
(55, N'Third Party', 85, N'TP Driver (DOC)', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdparty_adm', N'Third Party', N'NO', N'NO', N'YES'),
(55, N'Third Party', 86, N'TP Driver (Theft)', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'allegedvandal_adm', N'Alleged Vandal/Thief', N'NO', N'NO', N'NO'),
(55, N'Third Party', 87, N'TP Passenger', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdpartypassenger_adm', N'Third Party Passenger', N'NO', N'YES', N'NO'),
(55, N'Third Party', 88, N'PH Passenger', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'passenger', N'PH Passenger', N'NO', N'NO', N'NO'),
(55, N'Third Party', 89, N'Motorcyclist', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'mtrcyclist_driver_adm', N'Motorcyclist Driver', N'NO', N'YES', N'NO'),
(55, N'Third Party', 90, N'Pillion Passenger', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'mtrcyclist_pssngr_adm', N'Motorcyclist Passenger', N'NO', N'NO', N'YES'),
(55, N'Third Party', 91, N'Adult Pedestrian', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'pedestrian', N'Pedestrian', N'NO', N'NO', N'NO'),
(55, N'Third Party', 92, N'Child Pedestrian', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'pedestrian', N'Pedestrian', N'NO', N'NO', N'NO'),
(55, N'Third Party', 93, N'Adult Cyclist', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'cyclist', N'Cyclist', N'NO', N'NO', N'NO'),
(55, N'Third Party', 94, N'Child Cyclist', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'cyclist', N'Cyclist', N'NO', N'NO', N'NO'),
(55, N'Third Party', 95, N'TP Vehicle Owner', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdparty_adm', N'Third Party', N'NO', N'NO', N'YES'),
(55, N'Third Party', 96, N'Registered Keeper', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdparty_adm', N'Third Party', N'NO', N'NO', N'YES'),
(55, N'Third Party', 97, N'TP Property Owner', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdparty_adm', N'Third Party', N'NO', N'NO', N'YES'),
(55, N'Third Party', 98, N'Company', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdparty_adm', N'Third Party', N'NO', N'NO', N'YES'),
(55, N'Third Party', 292, N'Registered Bank Address', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdparty_adm', N'Third Party', N'NO', N'NO', N'YES'),
(55, N'Third Party', 2080, N'TP Driver (Company)', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdparty_adm', N'Third Party', N'NO', N'NO', N'YES'),
(55, N'Third Party', 10013, N'Payee', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdparty_adm', N'Third Party', N'NO', N'NO', N'YES'),
(62, N'Authorised Caller', 40, N'Father', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(62, N'Authorised Caller', 41, N'Mother', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(62, N'Authorised Caller', 44, N'Sister', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(62, N'Authorised Caller', 43, N'Brother', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(62, N'Authorised Caller', 136, N'Daughter', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(62, N'Authorised Caller', 137, N'Other', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(62, N'Authorised Caller', 138, N'Personal Assistant', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(62, N'Authorised Caller', 139, N'Neighbour', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(62, N'Authorised Caller', 140, N'Friend', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(62, N'Authorised Caller', 156, N'Son', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(62, N'Authorised Caller', 280, N'Spouse/Partner', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(62, N'Authorised Caller', 289, N'Employee', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(63, N'Authorised Caller', 45, N'Father', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'altcontact', N'Authorised Caller', N'NO', N'YES', N'NO'),
(63, N'Authorised Caller', 46, N'Mother', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'altcontact', N'Authorised Caller', N'NO', N'YES', N'NO'),
(63, N'Authorised Caller', 281, N'Other', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'altcontact', N'Authorised Caller', N'NO', N'YES', N'NO'),
(63, N'Authorised Caller', 9990, N'Daughter', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'altcontact', N'Authorised Caller', N'NO', N'YES', N'NO'),
(63, N'Authorised Caller', 9992, N'Brother', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'altcontact', N'Authorised Caller', N'NO', N'YES', N'NO'),
(63, N'Authorised Caller', 9993, N'Sister', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'altcontact', N'Authorised Caller', N'NO', N'YES', N'NO'),
(63, N'Authorised Caller', 9994, N'Personal Assistant', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'altcontact', N'Authorised Caller', N'NO', N'YES', N'NO'),
(63, N'Authorised Caller', 9995, N'Neighbour', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'altcontact', N'Authorised Caller', N'NO', N'YES', N'NO'),
(63, N'Authorised Caller', 9996, N'Friend', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'altcontact', N'Authorised Caller', N'NO', N'YES', N'NO'),
(63, N'Authorised Caller', 9997, N'Son', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'altcontact', N'Authorised Caller', N'NO', N'YES', N'NO'),
(63, N'Authorised Caller', 9998, N'Spouse/Partner', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'altcontact', N'Authorised Caller', N'NO', N'YES', N'NO'),
(64, N'Witness', 65, N'Independent', N'Motor', N'GW MOTOR AD', NULL, N'witness', N'Witness', N'NO', N'YES', N'NO'),
(64, N'Witness', 66, N'Non-Independent', N'Motor', N'GW MOTOR AD', NULL, N'witness', N'Witness', N'NO', N'YES', N'NO'),
(65, N'Witness', 67, N'Independent', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'witness', N'Witness', N'NO', N'YES', N'NO'),
(65, N'Witness', 68, N'Non-Independent', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'witness', N'Witness', N'NO', N'YES', N'NO'),
(66, N'Police', 63, N'Attending Officer', N'Motor', N'GW MOTOR AD', NULL, N'policeofficer_adm', N'Police Officer', N'NO', N'NO', N'NO'),
(66, N'Police', 64, N'Report Application', N'Motor', N'GW MOTOR AD', NULL, N'policeofficer_adm', N'Police Officer', N'NO', N'NO', N'NO'),
(66, N'Police', 10000, N'Police Report Payment', N'Motor', N'GW MOTOR AD', NULL, N'policeofficer_adm', N'Police Officer', N'NO', N'NO', N'NO'),
(66, N'Police', 10017, N'Reported to Station', N'Motor', N'GW MOTOR AD', NULL, N'policeofficer_adm', N'Police Officer', N'NO', N'NO', N'NO'),
(71, N'Salvage Agent', 74, N'Approved', N'Motor', N'GW MOTOR AD', NULL, N'salvageservice', N'Salvage Agent', N'NO', N'YES', N'NO'),
(71, N'Salvage Agent', 143, N'Non-Approved', N'Motor', N'GW MOTOR AD', NULL, N'salvageservice', N'Salvage Agent', N'NO', N'YES', N'NO'),
(72, N'Salvage Agent', 75, N'Approved', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'salvageservice', N'Salvage Agent', N'NO', N'YES', N'NO'),
(72, N'Salvage Agent', 144, N'Non-Approved', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'salvageservice', N'Salvage Agent', N'NO', N'YES', N'NO'),
(73, N'Finance', 76, N'Finance', N'Motor', N'GW MOTOR AD', NULL, N'finance_adm', N'Finance', N'NO', N'YES', N'NO'),
(74, N'Finance', 77, N'Finance', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'finance_adm', N'Finance', N'NO', N'YES', N'NO'),
(75, N'GAP', 78, N'GAP', N'Motor', N'GW MOTOR AD', NULL, N'gap_adm', N'GAP', N'NO', N'YES', N'NO'),
(76, N'GAP', 79, N'GAP', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'gap_adm', N'GAP', N'NO', N'YES', N'NO'),
(77, N'Medical Centre', 100, N'Hospital', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'hospital', N'Hospital', N'NO', N'YES', N'NO'),
(77, N'Medical Centre', 101, N'GP', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'hospital', N'Hospital', N'NO', N'YES', N'NO'),
(77, N'Medical Centre', 102, N'Roadside examination', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'hospital', N'Hospital', N'NO', N'YES', N'NO'),
(77, N'Medical Centre', 103, N'Walk in centre', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'hospital', N'Hospital', N'NO', N'YES', N'NO'),
(78, N'CRU', 104, N'CRU', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(79, N'Registered Keeper', 105, N'Registered Keeper', N'Motor', N'GW MOTOR AD', NULL, N'registeredkeeper_adm', N'Registered Keeper', N'NO', N'YES', N'NO'),
(80, N'Registered Keeper', 106, N'Registered Keeper', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'registeredkeeper_adm', N'Registered Keeper', N'NO', N'YES', N'NO'),
(81, N'Credit Hire', 119, N'Credit Hire Company', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'credithirecompany_adm', N'Credit Hire Company', N'NO', N'YES', N'NO'),
(82, N'Approved Repairer', 111, N'Bodyshop', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'repairshop', N'Approved Repairer', N'NO', N'NO', N'YES'),
(82, N'Approved Repairer', 142, N'Payee', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'repairshop', N'Approved Repairer', N'NO', N'NO', N'YES'),
(82, N'Approved Repairer', 3063, N'Hub Instructed Bodyshop', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'repairshop', N'Approved Repairer', N'NO', N'NO', N'YES'),
(83, N'Solicitor', 282, N'Panel Solicitor', N'Motor', N'GW MOTOR AD', NULL, N'panelsolicitor_adm', N'Panel Solicitor', N'NO', N'NO', N'NO'),
(83, N'Solicitor', 112, N'Solicitor', N'Motor', N'GW MOTOR AD', NULL, N'insuredRep', N'Insured Representative', N'NO', N'NO', N'NO'),
(84, N'Rehabilitation', 113, N'Rehab Supplier', N'Motor', N'GW MOTOR AD', NULL, N'rehabilitation_adm', N'Rehabilitation', N'NO', N'NO', N'NO'),
(85, N'Accident Management', 114, N'Accident Management', N'Motor', N'GW MOTOR AD', NULL, N'casemgmtco', N'Accident Management Co', N'NO', N'YES', N'NO'),
(86, N'Accident Management', 115, N'Accident Management', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'casemgmtco', N'Accident Management Co', N'NO', N'YES', N'NO'),
(87, N'Assessor', 116, N'Approved', N'Motor', N'GW MOTOR AD', NULL, N'assessor', N'Assessor', N'NO', N'YES', N'NO'),
(87, N'Assessor', 6000, N'Non Approved', N'Motor', N'GW MOTOR AD', NULL, N'assessor', N'Assessor', N'NO', N'YES', N'NO'),
(88, N'Assessor', 117, N'Approved', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'assessor', N'Assessor', N'NO', N'YES', N'NO'),
(88, N'Assessor', 6001, N'Non Approved', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'assessor', N'Assessor', N'NO', N'YES', N'NO'),
(89, N'Broker', 118, N'Broker', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'broker_adm', N'Broker', N'NO', N'NO', N'NO'),
(90, N'Credit Repair', 135, N'Credit Repair Company', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'creditrepaircompany_adm', N'Credit Repair Company', N'NO', N'NO', N'NO'),
(91, N'Employer', 120, N'Employer', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'employer', N'Employer', N'NO', N'YES', N'NO'),
(92, N'Foreign Agent/Insurer', 121, N'Foreign Agent/Insurer', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'foreignagent_adm', N'Foreign Agent/Insurer', N'NO', N'NO', N'NO'),
(93, N'Investigator', 122, N'Investigator', N'Motor', N'GW MOTOR AD', NULL, N'investigator_adm', N'Investigator', N'NO', N'NO', N'NO'),
(95, N'NON AR', 124, N'Bodyshop', N'Motor', N'GW MOTOR AD', NULL, N'nonapprovedrepairer_adm', N'Non - Approved Repairer', N'NO', N'YES', N'NO'),
(95, N'NON AR', 9999, N'Payee', N'Motor', N'GW MOTOR AD', NULL, N'nonapprovedrepairer_adm', N'Non - Approved Repairer', N'NO', N'YES', N'NO'),
(96, N'Other', 125, N'Other', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(97, N'Other', 126, N'Other', N'Motor', N'GW MOTOR AD', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(98, N'Solicitor', 127, N'Solicitor', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdpartysolicitor_adm', N'Third Party Solicitor', N'NO', N'YES', N'NO'),
(98, N'Solicitor', 128, N'Panel Solicitor', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'panelsolicitor_adm', N'Panel Solicitor', N'NO', N'NO', N'NO'),
(100, N'UK Handling Agent', 129, N'UK Handling Agent', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'ukhandlingagent_adm', N'UK Handling Agent', N'NO', N'NO', N'NO'),
(101, N'Vehicle Recovery', 130, N'Approved', N'Motor', N'GW MOTOR AD', NULL, N'recoveryagent', N'Recovery Agent', N'NO', N'NO', N'NO'),
(101, N'Vehicle Recovery', 131, N'Non-Approved', N'Motor', N'GW MOTOR AD', NULL, N'recoveryagent', N'Recovery Agent', N'NO', N'NO', N'NO'),
(101, N'Vehicle Recovery', 5006, N'Vehicle Location', N'Motor', N'GW MOTOR AD', NULL, N'recoveryagent', N'Recovery Agent', N'NO', N'NO', N'NO'),
(102, N'Vehicle Recovery', 132, N'Approved', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'recoveryagent', N'Recovery Agent', N'NO', N'NO', N'YES'),
(102, N'Vehicle Recovery', 133, N'Non-Approved', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'recoveryagent', N'Recovery Agent', N'NO', N'NO', N'YES'),
(102, N'Vehicle Recovery', 5007, N'Vehicle Location', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'recoveryagent', N'Recovery Agent', N'NO', N'NO', N'YES'),
(103, N'CCTV/Footage', 134, N'CCTV/Footage', N'Motor', N'GW MOTOR AD', NULL, N'witness', N'Witness', N'NO', N'YES', N'NO'),
(104, N'CCTV/Footage', 274, N'CCTV/Footage', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'witness', N'Witness', N'NO', N'YES', N'NO'),
(105, N'Reinsurance', 146, N'Direct', N'Motor', N'GW HEADER CASE', NULL, N'reinsurance_adm', N'Reinsurance', N'NO', N'NO', N'NO'),
(105, N'Reinsurance', 147, N'Broker', N'Motor', N'GW HEADER CASE', NULL, N'reinsurance_adm', N'Reinsurance', N'NO', N'NO', N'NO'),
(106, N'UIL', 145, N'ULR Company', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'ulrcompany_adm', N'ULR Company', N'NO', N'NO', N'NO'),
(107, N'Hoods', 150, N'Hoods', N'Motor', N'GW MOTOR AD', NULL, N'hoods_adm', N'Hoods', N'NO', N'NO', N'NO'),
(108, N'Hire Ancillary Provider', 149, N'Hire Ancillary Provider', N'Motor', N'GW MOTOR AD', NULL, N'hireancillary_adm', N'Hire Ancillary Provider', N'NO', N'NO', N'NO'),
(109, N'Loss Adjuster', 148, N'Loss Adjuster', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'lossasses_adm', N'Loss Assessor', N'NO', N'NO', N'NO'),
(111, N'Fire Service', 151, N'Fire Service', N'Motor', N'GW MOTOR AD', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(112, N'Hoods', 152, N'Hoods', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'hoods_adm', N'Hoods', N'NO', N'NO', N'NO'),
(138, N'Accident Location', 257, N'Accident Location', N'Motor', N'GW HEADER CASE', NULL, N'other', N'Other', N'NO', N'NO', NULL)  -- ROW 131: Link_to_Incident was 'NC' - left NULL pending confirmation,
(139, N'Accident Location', 258, N'Accident Location', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(140, N'Accident Location', 259, N'Accident Location', N'Motor', N'GW MOTOR AD', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(141, N'Police Compound', 260, N'Compound', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'policeofficer_adm', N'Police Officer', N'NO', N'NO', N'NO'),
(142, N'Police Compound', 261, N'Compound', N'Motor', N'GW MOTOR AD', NULL, N'policeofficer_adm', N'Police Officer', N'NO', N'NO', N'NO'),
(143, N'Other Vehicle Location', 262, N'Vehicle Location', N'Motor', N'GW MOTOR AD', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(144, N'Other Vehicle Location', 263, N'Vehicle Location', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(145, N'Side of Road', 264, N'Side of Road', N'Motor', N'GW MOTOR AD', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(146, N'Side of Road', 265, N'Side of Road', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(147, N'Rehabilitation', 283, N'Rehab Supplier', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'rehabilitation_adm', N'Rehabilitation', N'NO', N'NO', N'NO'),
(148, N'Storage Yard', 2821, N'Storage Yard', N'Motor', N'GW MOTOR AD', NULL, N'storageyard_adm', N'Storage Yard', N'NO', N'NO', N'NO'),
(149, N'Storage Yard', 2822, N'Storage Yard', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'storageyard_adm', N'Storage Yard', N'NO', N'NO', N'NO'),
(150, N'Telematics Provider', 284, N'Telematics Provider', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(164, N'Public Liability Insurer', 285, N'Public Liability Insurer', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(165, N'Public Liability Insurer', 286, N'Public Liability Insurer', N'Motor', N'GW MOTOR AD', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(166, N'Employers Liability Insurance', 287, N'Employers Liability Insurance', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(167, N'Employers Liability Insurance', 288, N'Employers Liability Insurance', N'Motor', N'GW MOTOR AD', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(168, N'Counsel', 290, N'Counsel', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'counsel_adm', N'Counsel', N'NO', N'NO', N'NO'),
(169, N'Court', 291, N'Court', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'hearingvenue', N'Court', N'NO', N'YES', N'NO'),
(5024, N'DOC Vehicle Owner', 232, N'Vehicle Owner', N'Motor', N'GW HEADER CASE', NULL, N'docvehicleowner_adm', N'DOC Owner', N'NO', N'NO', N'NO'),
(5025, N'DOC Vehicle Insurer', 233, N'Vehicle Insurer', N'Motor', N'GW HEADER CASE', NULL, N'docvehicleinsurer_adm', N'DOC Vehicle Insurer', N'NO', N'NO', N'NO'),
(5026, N'Hire Company', 235, N'Head Office', N'Motor', N'GW MOTOR AD', NULL, N'hirecompany_adm', N'Hire Company', N'NO', N'NO', N'NO'),
(5027, N'Hire Company', 236, N'Head Office', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'hirecompany_adm', N'Hire Company', N'NO', N'NO', N'YES'),
(5028, N'Authorised Driver', 245, N'Authorised Driver', N'Motor', N'GW MOTOR AD', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(5029, N'Authorised Driver', 246, N'Authorised Driver', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(5030, N'NFS Supplier', 256, N'NFS Supplier', N'Motor', N'GW MOTOR AD', NULL, N'nfssupplier_adm', N'NFS Supplier', N'NO', N'NO', N'NO'),
(5030, N'NFS Supplier', 5008, N'Vehicle Location', N'Motor', N'GW MOTOR AD', NULL, N'nfssupplier_adm', N'NFS Supplier', N'NO', N'NO', N'NO'),
(5051, N'Solicitor', 1003, N'Solicitor', N'Motor', N'GW PA Ancillary', NULL, N'InsuredRep', N'Insured Representative', N'NO', N'NO', N'NO'),
(5052, N'Doctor', 1004, N'Doctor', N'Motor', N'GW PA Ancillary', NULL, N'doctor', N'Doctor', N'NO', N'YES', N'NO'),
(5053, N'ULR', 1005, N'ULR', N'Motor', N'GW PA Ancillary', NULL, N'ulrcompany_adm', N'ULR Company', N'NO', N'NO', N'NO'),
(5054, N'Family member', 1006, N'Mother', N'Motor', N'GW PA Ancillary', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(5054, N'Family member', 1007, N'Father', N'Motor', N'GW PA Ancillary', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(5054, N'Family member', 1008, N'Sister', N'Motor', N'GW PA Ancillary', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(5054, N'Family member', 1009, N'Brother', N'Motor', N'GW PA Ancillary', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(5054, N'Family member', 1010, N'Other', N'Motor', N'GW PA Ancillary', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(5059, N'Named Driver', 253, N'Correspondence Information', N'Motor', N'GW HEADER CASE', NULL, N'listeddriver_adm', N'Named Driver', N'NO', N'YES', N'NO'),
(5059, N'Named Driver', 1011, N'Named Driver', N'Motor', N'GW HEADER CASE', NULL, N'listeddriver_adm', N'Named Driver', N'NO', N'YES', N'NO'),
(5059, N'Named Driver', 10005, N'Next of Kin', N'Motor', N'GW HEADER CASE', NULL, N'listeddriver_adm', N'Named Driver', N'NO', N'YES', N'NO'),
(5059, N'Named Driver', 51, N'Correspondence Information', N'Motor', N'GW HEADER CASE', NULL, N'listeddriver_adm', N'Named Driver', N'NO', N'YES', N'NO'),
(5070, N'ULR Company', 1016, N'ULR Company', N'Motor', N'GW MOTOR AD', NULL, N'ulrcompany_adm', N'ULR Company', N'NO', N'NO', N'NO'),
(5071, N'Other Insurer', 1017, N'Other Insurer', N'Motor', N'GW MOTOR AD', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(5071, N'Other Insurer', 5000, N'Previous Insurer', N'Motor', N'GW MOTOR AD', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(5071, N'Other Insurer', 5001, N'Dual Insurer', N'Motor', N'GW MOTOR AD', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(5071, N'Other Insurer', 5002, N'S29 Request Insurer', N'Motor', N'GW MOTOR AD', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(5077, N'Alternative Insurer', 2012, N'Vehicle Insurer', N'Motor', N'GW HEADER CASE', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(5089, N'Recovery Agent/Garage', 2013, N'Compound', N'Motor', N'GW MOTOR AD', NULL, N'recoveryagent', N'Recovery Agent', N'NO', N'NO', N'NO'),
(5089, N'Recovery Agent Garage', 5009, N'Vehicle Location', N'Motor', N'GW MOTOR AD', NULL, N'recoveryagent', N'Recovery Agent', N'NO', N'NO', N'NO'),
(5090, N'Recovery Agent Garage', 2014, N'Compound', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'recoveryagent', N'Recovery Agent', N'NO', N'NO', N'YES'),
(5090, N'Recovery Agent Garage', 5010, N'Vehicle Location', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'recoveryagent', N'Recovery Agent', N'NO', N'NO', N'YES'),
(5091, N'Uninjured Passenger', 2015, N'Uninjured Passenger', N'Motor', N'GW MOTOR AD', NULL, N'passenger', N'PH Passenger', N'NO', N'NO', N'NO'),
(5092, N'Uninjured Passenger', 2016, N'Uninjured Passenger', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdpartypassenger_adm', N'Third Party Passenger', N'NO', N'YES', N'NO'),
(5101, N'Authorised Payee', 6015, N'Authorised Payee', N'Motor', N'GW PA Ancillary', NULL, N'Payee_Adm', N'Payee', N'NO', N'YES', N'NO'),
(5104, N'Previous Keeper', 8888, N'Previous Keeper', N'Motor', N'GW MOTOR AD', NULL, N'previouskeeper_adm', N'Previous Keeper', N'NO', N'NO', N'NO'),
(5105, N'Parent/Guardian', 8887, N'Parent/Guardian', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(5106, N'Medical Centre', 10001, N'Hospital', N'Motor', N'GW PA Ancillary', NULL, N'hospital', N'Hospital', N'NO', N'YES', N'NO'),
(5106, N'Medical Centre', 10002, N'OP', N'Motor', N'GW PA Ancillary', NULL, N'hospital', N'Hospital', N'NO', N'YES', N'NO'),
(5106, N'Medical Centre', 10003, N'Roadside examination', N'Motor', N'GW PA Ancillary', NULL, N'hospital', N'Hospital', N'NO', N'YES', N'NO'),
(5106, N'Medical Centre', 10004, N'Walk in centre', N'Motor', N'GW PA Ancillary', NULL, N'hospital', N'Hospital', N'NO', N'YES', N'NO'),
(5107, N'Other', 100005, N'Other', N'Motor', N'GW PA Ancillary', NULL, N'other', N'Other', N'NO', N'YES', N'NO'),
(5108, N'Dependent', 10006, N'Father', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'claimantdep', N'Dependent', N'NO', N'YES', N'NO'),
(5108, N'Dependent', 10007, N'Mother', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'claimantdep', N'Dependent', N'NO', N'YES', N'NO'),
(5108, N'Dependent', 10008, N'Brother', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'claimantdep', N'Dependent', N'NO', N'YES', N'NO'),
(5108, N'Dependent', 10009, N'Sister', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'claimantdep', N'Dependent', N'NO', N'YES', N'NO'),
(5108, N'Dependent', 10010, N'Son', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'claimantdep', N'Dependent', N'NO', N'YES', N'NO'),
(5108, N'Dependent', 10011, N'Daughter', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'claimantdep', N'Dependent', N'NO', N'YES', N'NO'),
(5108, N'Dependent', 10012, N'Other', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'claimantdep', N'Dependent', N'NO', N'YES', N'NO'),
(5109, N'Windscreen Supplier', 10016, N'Windscreen Supplier', N'Motor', N'GW MOTOR AD', NULL, N'wscsupplier_adm', N'WSC Supplier', N'NO', N'NO', N'NO'),
(5201, N'Other Insurer', 1018, N'Other Insurer', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(5201, N'Other Insurer', 5003, N'Previous Insurer', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(5201, N'Other Insurer', 5004, N'Dual Insurer', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(5201, N'Other Insurer', 5005, N'S29 Request Insurer', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'alternativeinsurer_adm', N'Alternative Insurer', N'NO', N'NO', N'NO'),
(5210, N'Medical Evidence', 10020, N'Medical Records', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'hospital', N'Hospital', N'NO', N'YES', N'NO'),
(5210, N'Medical Evidence', 10021, N'Medical Expert', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'medicalexpert_adm', N'Medical Expert', N'NO', N'YES', N'NO'),
(5314, N'Policy Authorised Caller', 5314, N'Policy Authorised Caller', N'Motor', N'GW HEADER CASE', NULL, N'altcontact', N'Authorised Caller', N'NO', N'NO', N'NO'),
(5403, N'Driving Licence Authority', 3064, N'Driving Licence Authority', N'Motor', N'GW MOTOR AD', NULL, N'dvla_adm', N'DVLA', N'NO', N'NO', N'NO'),
(5404, N'Driving Licence Authority', 3065, N'Driving Licence Authority', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'dvla_adm', N'DVLA', N'NO', N'NO', N'NO'),
(5405, N'Coroner', 3066, N'Coroner', N'Motor', N'GW MOTOR AD', NULL, N'coroner_adm', N'Coroner', N'NO', N'NO', N'NO'),
(5406, N'Coroner', 3067, N'Coroner', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'coroner_adm', N'Coroner', N'NO', N'NO', N'NO'),
(55555, N'Driver Not On Cover', 1013, N'Driver Not On Cover', N'Motor', N'GW HEADER CASE', NULL, N'driver_notoncover_adm', N'Driver not on cover', N'NO', N'NO', N'NO'),
(83, N'Solicitor', 1016, N'ULR Company', N'Motor', N'GW MOTOR AD', NULL, N'InsuredRep', N'Insured Representative', N'NO', N'NO', N'NO'),
(55, N'Third Party', 99, N'Alleged Vandal', N'Motor', N'GW MOTOR THIRDPARTY', NULL, N'thirdparty_adm', N'Third Party', N'NO', N'NO', N'YES');